language: node_js

node_js:
  - "12"

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/greetingsTests

before_script:
  - psql -c 'create database  greetingsTests;' -U postgres
  - psql -U postgres -d greetingsTests -a -f tables.sql

services:
  - postgresql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2
