language: node_js

node_js:
  - "12"

env:
  - process.env.DATABASE_URL

before_script:
  - psql -c 'create database  greetingsTests;' -U postgres
  - psql -U postgres -d greetingsTests -a -f tables.sql

services:
  - postgresql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2
