language: node_js

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/greet_tests

node_js:
  - "12"

before_script:
  - psql -c 'create database  greet_tests;' -U postgres
  - psql -U postgres -d greet_tests -a -f table.sql

services:
  - postgresql

addons:
    apt:
    packages:
    - postgresql-server-dev-9.2
